name: ALE Psych Builds

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform }}
    permissions: write-all
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - platform: Windows
            os: windows-latest
            container:
            haxe_setup:
            build_cmd: haxelib run lime build windows
            extra_libs:
            pre_build_commands:
            artifact_path: export/release/windows/bin
            
    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        if: ${{ !matrix.haxe_setup }}
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Custom Haxe Setup
        if: ${{ matrix.haxe_setup }}
        run: ${{ matrix.haxe_setup }}

      - name: Install Main Libraries
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install

      - name: Install Extra Libraries
        if: ${{ matrix.extra_libs }}
        run: ${{ matrix.extra_libs }}

      - name: Pre-Build Commands
        if: ${{ matrix.pre_build_commands }}
        run: ${{ matrix.pre_build_commands }}

      - name: Build for ${{ matrix.platform }}
        run: ${{ matrix.build_cmd }}

      - name: Upload Game
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }} Build
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
