name: iOS Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-15

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Set XCode app
        if: inputs.os == 'macos-15'
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install Libraries
        run: sh ./setup/install-haxelibs.sh
        
      - name: Build for iOS
        run: haxelib run lime build ios -nosign

      - name: Upload Game
        uses: actions/upload-artifact@main
        with:
          name: iOS Build
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error